#' @importFrom stats spec.ar
#' @importFrom slider slide_dbl
#' @importFrom stats na.omit
#' @importFrom purrr map
#' @importFrom neuralnet neuralnet
#' @importFrom distributional dist_sample
#' @importFrom distributional dist_normal
#' @importFrom tsibble measured_vars
#' @importFrom fabletools new_specials
#' @importFrom rlang warn
#' @importFrom glue glue
#' @importFrom rlang abort
#' @importFrom fabletools new_model_class
#' @importFrom tsibble is_regular
#' @importFrom fabletools new_model_definition
#' @importFrom rlang enquo
#' @importFrom purrr reduce
#' @importFrom dplyr lag
#' @importFrom purrr safely
#' @importFrom feasts unitroot_ndiffs
#' @importFrom feasts unitroot_nsdiffs
#' @importFrom purrr partial
NULL
