#' @importFrom stats runif
#' @importFrom stats median
#' @importFrom purrr map
#' @importFrom stats predict
#' @importFrom stats spec.ar
#' @importFrom slider slide_dbl
#' @importFrom stats na.omit
#' @importFrom stats as.formula
#' @importFrom mgcv gam
#' @importFrom stats rnorm
#' @importFrom stats rchisq
#' @importFrom mboost Gaussian
#' @importFrom mboost boost_control
#' @importFrom partykit ctree_control
#' @importFrom mboost blackboost
#' @importFrom neuralnet neuralnet
#' @importFrom distributional dist_sample
#' @importFrom distributional dist_normal
#' @importFrom stats var
#' @importFrom tsibble measured_vars
#' @importFrom fabletools new_specials
#' @importFrom rlang warn
#' @importFrom glue glue
#' @importFrom rlang abort
#' @importFrom rlang enexprs
#' @importFrom rlang enquos
#' @importFrom rlang get_env
#' @importFrom purrr map_lgl
#' @importFrom purrr compose
#' @importFrom rlang is_empty
#' @importFrom rlang env_parents
#' @importFrom rlang new_formula
#' @importFrom purrr reduce
#' @importFrom rlang call2
#' @importFrom stats model.frame
#' @importFrom stats na.pass
#' @importFrom fabletools new_model_class
#' @importFrom tsibble is_regular
#' @importFrom fabletools new_model_definition
#' @importFrom rlang enquo
#' @importFrom stats wilcox.test
#' @importFrom dplyr lag
#' @importFrom purrr imap
#' @importFrom stats diffinv
#' @importFrom purrr safely
#' @importFrom feasts unitroot_ndiffs
#' @importFrom feasts unitroot_nsdiffs
#' @importFrom purrr partial
#' @importFrom utils tail
#' @importFrom xgboost xgb.DMatrix
#' @importFrom xgboost xgboost
NULL
